#!/bin/bash
GREEN='\033[0;32m'
RED='\033[0;31m'

declare -i depcount=0
echo -e "${GREEN} Checking Dependencies"
err(){
	echo -e "${RED} ERROR: $1" 2>&1
	echo ""
}
for i in /usr/bin/{yad,zenity}
	do
		[ -x "$i" ] || {
			err "Dependency $i Not Met"
			depcount+=1
		}
	done

[ $depcount -eq 0 ] || exit 1
echo ""
echo -e "${GREEN} Dependencies Met"
zenity --info --text="<span font='12'>This Software Comes With <b>Absolutely No Warranty</b> 🚫\n\nIn The Very Unlikely Case That You Make A Million Bucks Off This Software 💰, Congratulations 🎊, Consider Buying Grams Of Cocaine And Weed 🌿</span>\n\n\n\t\Made With ❤ By Dharmy️" --title="Disclaimer" --width=400 2>/dev/null
zenity --info --text="<span font='12'>Your Password Will Be Needed To Perform Some Core Installation Functions. Please Be Aware That Your Password Is In <b>No Way Being Stored Or Cached</b> Anywhere\n\nIn Any Case You Do Not Trust This Program, Press Cancel On The Next Dialog To Abort Installation</span>" --title="Password Disclaimer" --width=400 2>/dev/null
pass="$( zenity --password 2>/dev/null )"
if [[ ${?} != 0 || -z ${pass} ]]
then
    zenity --error --text="No password entered" 2>/dev/null
    exit 4
fi

if ! sudo -kSp '' [ 1 ] <<<"${pass}" 2>/dev/null
then
    zenity --error --text="Incorrect password" 2>/dev/null
    exit 4
fi

[ -d ~/.schedule/ ] || mkdir ~/.schedule
operation(){
	sudo -Sp '' $1 <<<"${pass}"
}
operation "mkdir -p /usr/share/Scheduler/"
(
	echo "#Hold On, This Will Take Just A Second"; sleep 3
	echo "10"	
	operation "cp ./bin/schedule /usr/bin/"
	echo "#Wait, It's Been A Second Already?" ; sleep 2
	echo "20"
	operation "chmod +x /usr/bin/schedule"
	echo "#Okay, Hold On Another Second" ; sleep 3
	echo "30"
	operation "cp ./bin/icons/48x48/scheduler.png /usr/share/pixmaps/"
	echo "#This Is The Second Time I'm Asking For A Second" ; sleep 3
	echo "40"
	echo "#Now, This Is The Second Where I Ask For Another Second" ; sleep 3
	echo "50"
	operation "cp ./bin/schedule.desktop /usr/share/applications"
	echo "#Can I Please Be Spared Another Second From Your Time?" ; sleep 3
	echo "60"
	operation "chmod +x /usr/share/applications/schedule.desktop" ; sleep 2
	operation "cp ./bin/uninstaller /usr/share/Scheduler/" 
	operation "chmod +x /usr/share/Scheduler/uninstaller"
	echo "#I Swear This Is The Last Time I'll Ask For An...... Oh, I'm Done"
	echo "100"
) | yad --progress \
	--center \
	--title="Installing" \
	--pulsate \
	--width=500 \
	2>/dev/null

	[ $? -eq 0 ] || {
		yad --center --image dialog-error --title "User Abort" --text="<span font='10'>You Couldn't Just Give All The Seconds I Needed</span>\n\nInstallation Aborted" --width=300 2>/dev/null
		exit 0
	}

yad --center --text "<span font='12'>Installation Finished</span>\n\nYou Can Launch Schedule From Your App Drawer" --button="gtk-ok" 2>/dev/null