#!/bin/bash -x
x=()
icon_trigger=0
config=~/.schedule/scheduler.conf
export -f $config
#nl=`< $config wc -l`
#m scared ill fail this course
arg=$1
if ! [ -f "$config" ]; then
	touch $config
fi
add_todo(){
	zenity --forms --title="Wassup" --add-entry="Course Title" --add-entry="Course Code" --add-entry="Units" --add-calendar="Date" --forms-date-format='%A %d %Y' 1>>"$config" --width=400 2>/dev/null
	list_todo
}
	export -f add_todo

list_todo(){
	x=()
	ln=1
	while read -r todo || [[ -n "$todo" ]]; do
		x+=($ln)
		ln=$((ln+1))
		IFS="|"; for i in $todo; do
			if [ "$i" == "" ]; then
				i="-";
			fi
			x+=($i)
		done
	done < "$config"
		if [ "$ln" == "1" ]; then
	yad --text="Your To-Do List Is Spick Span\n\nWould You Like To Add A Task?" --title="Empty" --button="Yes:1" --button="No:0" --width=400 2>/dev/null
	ch=$?
	export $ch
	if [ "$ch" == "1" ]; then
		add_todo
	fi
	exit 0
fi
	yad --list --center --title="TO-DO" --text="Here Are Your Stuff To-Do" --column="S/N" --column="Course Title" --column="Course Code" --column="Units" --column="Date" ${x[*]} --width=600 --height=600 --no-selection --button="Remove:2" --button="Add:1" --button="Ok:0" >/dev/null 2>&1
	ch=$?
		if [ $ch -eq 1 ]; then
			add_todo
		elif [ $ch -eq 2 ]; then
			remove_todo
		else
			echo "TEst"
			if [ "$icon_trigger" == "0" ]; then
				icon_trigger=$(($icon_trigger+1))
			yad dialog-alert --center --text="The Schedule App Will Continue In The App Tray" --button="gtk-ok" --width=200 2>/dev/null
			icon_tray
		fi
		fi
}

export -f list_todo
remove_todo(){
	x=()
	y=0
	ln=1
	while read -r todo || [[ -n "$todo" ]]; do		
		x+=(false)		
		x+=($ln)
		ln=$((ln+1))
		IFS="|"; for i in $todo; do
			if [ "$i" == "" ]; then
				i="-";
			fi			
			x+=($i)			
		done
	done < "$config"
		if [ "$ln" == "1" ]; then
	zenity --info --text="Your To-Do List Is Spick Span" --title="Empty" --width=400 2>/dev/null
	exit 0
fi
tr=`zenity --list --checklist --title="TO-DO" --text="Choose Which To Remove" --column="Selection" --column="S/N" --column="Course Title" --column="Course Code" --column="Units" --column="Date" ${x[*]} --width=650 --height=600 2>/dev/null`
r_index=0
	IFS="|"; for i in $tr; do				
		if [ $i != 1 ] && [ $y != 0 ]; then
			i=$(($i-1))
		fi
		#f=`grep -n "$i" $config`
		#j=`sed 's/:.*//' <<<$f`
		sed -i ''$i'd' $config
		y=$(($y+1))		
	done	
	list_todo
}
export -f remove_todo
icon_tray(){
	export fifo=$(mktemp -u --tmpdir schedule.XXXXXXXX)
	mkfifo "$fifo"
	trap "rm -f $fifo" exit	
	on_click(){
		config=~/.schedule/scheduler.conf
		list_todo
	}
	export -f on_click

	menu_options(){
		echo "icon:scheduler"
		echo "menu:Add Todo!add_todo||List Todo!list_todo||Remove Todo!remove_todo||Quit!quit!gtk-quit"
		echo "tooltip:Schedule"
	}
	exec 3<>$fifo
	yad --notification --command="bash -c on_click" --listen <&3 & menu_options >&3
	exec 3>&-
}
if [ "$arg" == "--list" -o "$arg" == "-l" -o "$arg" == "" ]; then
	list_todo
elif [ "$arg" == "--remove" -o "$arg" == "-r" ]; then
	remove_todo
	
fi